version: "3.7"

services:
  echopost-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AZURE_MYSQL_CONNECTIONSTRING=Server=echopost-db; User ID=root; Password=password; Database=echopost
    ports:
      - "9637:5000"
    depends_on:
      echopost-db:
        condition: service_healthy
  echopost-db:
    image: arm64v8/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "echopost"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - echopost-db:/var/lib/mysql
# Names our volume
volumes:
  echopost-db:
